"""Regenerate the "What each file does" table in docs/ARCHITECTURE.md from
the About page's FILE_GROUPS, so the doc and the dialog never disagree.

    .venv\\Scripts\\python.exe tools\\gen_architecture_table.py

The table is written between the two marker comments in the doc; line
counts are read from the tree at run time.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from logfather.ui.about_page import FILE_GROUPS  # noqa: E402

START = "<!-- FILE TABLE: generated by tools/gen_architecture_table.py - do not edit by hand -->"
END = "<!-- END FILE TABLE -->"


def _lines(repo_path: str) -> str:
    path = REPO / repo_path
    if path.is_file():
        try:
            return str(sum(1 for _ in path.open(encoding="utf-8", errors="replace")))
        except OSError:
            return "-"
    if path.is_dir():
        total = 0
        for p in path.rglob("*.py"):
            total += sum(1 for _ in p.open(encoding="utf-8", errors="replace"))
        return f"{total} (all)"
    return "-"


def render() -> str:
    out = [START, ""]
    for group, blurb, entries in FILE_GROUPS:
        out.append(f"### {group}")
        out.append("")
        out.append(blurb)
        out.append("")
        out.append("| File | Lines | Purpose |")
        out.append("|---|---:|---|")
        for name, repo_path, summary in entries:
            out.append(f"| `{name}` | {_lines(repo_path)} | {summary} |")
        out.append("")
    out.append(END)
    return "\n".join(out)


def main() -> int:
    doc = REPO / "docs" / "ARCHITECTURE.md"
    text = doc.read_text(encoding="utf-8")
    a = text.find(START)
    b = text.find(END)
    if a < 0 or b < 0:
        print("markers not found in docs/ARCHITECTURE.md", file=sys.stderr)
        return 1
    new = text[:a] + render() + text[b + len(END):]
    doc.write_text(new, encoding="utf-8", newline="\n")
    print("docs/ARCHITECTURE.md table regenerated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
